name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.142.0/hugo_extended_0.142.0_linux_amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build with Hugo
        run: hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url}}/"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
